import Head from 'next/head'
import { Footer } from '@/components/Layout/Footer'
import { Navbar } from '@/components/Layout/Navbar'
import LandingBanner from '@/components/LandingBanner/banner'
import AboutUs from '@/components/LandingAboutUs/about'
import Events from '@/components/LandingEvent/event'
import Gallery from '@/components/Gallery/gallery'
import Unique from '@/components/LandingUnique/unique'
import FAQ from '@/components/FAQ/faq-index'
import SubscribeNewsLetter from '@/components/SubscribeNewsletter/subscribe-newsletter'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-ibtc-blue">
        <Navbar />
        <LandingBanner />
      </div>
      <AboutUs />
      <Events />
      <Gallery />
      <Unique />
      <SubscribeNewsLetter />
      <FAQ />
      <Footer />
    </>
  )
}
