import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 style={{border: "1px solid #cccccc", width: "50vw", margin: "30vh auto"}}>Hello Ibadan Techies Club</h1>
    </>
  )
}
