export { default as ArrowDecRight } from './ArrowDecoRight.svg'
export { default as ArrowDecLeft } from './ArrowDecoLeft.svg'
export { default as ArrowRight } from './arrow-right.svg'
export { default as OceanOrnament } from './OceanOrnament.svg'
export { default as OvalOrnament } from './OvalOrnament.svg'
export { default as ArrowDown } from './ArrowDown.svg'
export { default as SquiggleLeft } from './SquiggleLeft.svg'
export { default as SquiggleRight } from './SquiggleRight.svg'
