name: Triage

on:
  issue_comment:
    types:
      - created
      - edited
  workflow_call:

jobs:
  take-issue:
    name: Take issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    timeout-minutes: 10
    steps:
      - name: take an issue
        uses: bdougie/take-action@main
        with:
          message: Thanks for taking this on and trying to contribute to the Ibadan Techies! If you have not already, consider joining the club as a member. You can start from joining the conversation on our Discord (coming soon!) or Twitter.
          issueCurrentlyAssignedMessage: Thanks for being interested in this issue. It looks like this ticket is already assigned to a contributor. Please communicate with the assigned contributor to confirm the status of the issue.
          trigger: .take
          token: ${{ secrets.GITHUB_TOKEN }}
